console.log((false && undefined));
console.log((false || undefined));
console.log(((false && undefined) || (false || undefined)));
console.log(((false || undefined) || (false && undefined)));
console.log(((false && undefined) && (false || undefined)));
console.log(((false || undefined) && (false && undefined)));
console.log(('a' || (false && undefined) || ''));
console.log(((false && undefined) || 'a' || ''));
console.log(('a' && (false || undefined) && ''));
console.log(((false || undefined) && 'a' && ''));
